Feature/add tests
sitesmake/couriers_api pull request #5
Opened 2023-01-23 13:47 UTC by sitesmake

2023-01-23 14:05 UTC, abstractart commented
Не хватает гема который умеет считать тестовое покрытие кода в процентах (simplecov или что там сейчас актуально)

2023-01-24 07:23 UTC, abstractart requested changes

2023-01-24 07:23 UTC, abstractart commented on Gemfile
> +  gem 'factory_bot', '~> 6.2', '>= 6.2.1'
https://github.com/thoughtbot/factory_bot_rails мб лучше его заиспользуем?

2023-01-24 07:23 UTC, abstractart commented on coverage/.resultset.json
> +  "RSpec": {
Зачем все эти файлы в репозитории? Папка с coverage должна быть в gitignore

2023-01-24 07:23 UTC, abstractart commented on Gemfile
> +  gem 'simplecov', '~> 0.22.0'
Почему установил его в группу development? В доке советуют в группу test и прописать require false

https://github.com/simplecov-ruby/simplecov#getting-started

2023-01-24 14:32 UTC, sitesmake commented on Gemfile
> +  gem 'factory_bot', '~> 6.2', '>= 6.2.1'
done

2023-01-24 14:32 UTC, sitesmake commented on coverage/.resultset.json
> +  "RSpec": {
done

2023-01-24 14:32 UTC, sitesmake commented on Gemfile
> +  gem 'simplecov', '~> 0.22.0'
done

2023-01-24 16:50 UTC, abstractart approved these changes

2023-01-24 16:59 UTC, merged