Feature/ci GitHub actions
sitesmake/couriers_api pull request #7
Opened 2023-01-24 17:10 UTC by sitesmake

2023-01-24 17:41 UTC, abstractart commented on Gemfile
> +ruby "3.1.0"
Зачем версию поменял? Кстати, почему не используешь последнюю, вроде сейчас 3.2 актуальная

2023-01-24 17:46 UTC, abstractart requested changes

2023-01-24 17:46 UTC, abstractart commented on .github/workflows/ci.yml
> +        with:
Давай добавим кеширование зависимостей чтобы побыстрее это все работало
https://github.com/actions/cache/blob/main/examples.md#ruby---bundler

2023-01-24 17:46 UTC, abstractart commented on Gemfile
> +ruby "3.1.0"
Зачем версию поменял? Кстати, почему не используешь последнюю, вроде сейчас 3.2 актуальная

2023-01-25 10:46 UTC, sitesmake commented on Gemfile
> +ruby "3.1.0"
Последняя поддерживаемая 3.1
https://docs.github.com/en/github-ae@latest/actions/automating-builds-and-tests/building-and-testing-ruby?learn=continuous_integration

2023-01-25 11:52 UTC, abstractart approved these changes

2023-01-25 16:52 UTC, merged